

export  const languages = {
    en: {
        movies: 'movies',
        tvShows: 'tv shows',
        people: 'people',
        popular: 'popular',
        nowPlaying: 'now palying',
        upComing: 'up coming',
        topRated: 'top rated',
        airingToday: 'airing today',
        onTv: 'on tv',
        search: 'search',
        welcome: 'welcome',
        millionsOf: 'Millions of movies, TV shows and people to discover. Explore now.',
        today: 'today',
        thisWeek: 'this week',
        trending: 'trending',
        playTrailer: 'play trailer',
        overview: 'overview',
        freeToWatch: 'free To Watch',
        latestTrailer : "latest Trailer",
        searchPlaceholder: "Search for a movie,tv shows, person...." ,
        streaming: 'streaming',
        forRent: 'for rent',
        inTheatres : "in Theatres",
        allCrew: 'full cast & crew',
        viewMore: 'view more',
        viewAll: 'view all',
        seriesCast :'Series Top Billed Cast',
        Recommendations: 'Recommendations',
        similar: 'similar',
        media : 'media',
        backdrops: 'backdrops',
        stills : 'backdrops',
        videos: 'videos',
        posters: 'posters',
        social: 'social',
        reviews: 'reviews',
        readAllReviews: 'read all reviews',
        status: "status",
        originalLanguage: "original language",
        budget: "budget",
        revenue: "revenue",
        network: "network",
        keywords: "keywords",
        currentSeason: 'current season',
        seasons: 'المواسم',
        main: 'main',
        titles : 'alternative titles',
        castCrew:  'cast & crew',
        episodeGroups : 'episode groups',
        releaseDates : 'release dates',
        translations: 'translations',
        changes: 'changes',
        logos: 'logos',
        fandom: 'fandom',
        share: "share",
        shareLink : "share link",
        biography : "biography",
        knownFor: "Known For",
        personalInfo : "personal info",
        knownCredits: "Known Credits",
        gender: "gender",
        birthday: "Birthday",
        placeOfBirth: "Place of Birth",
        alsoKnownAs: "also known as",
        acting: "acting",
        all: "all",
        department: "department",
        profiles: "profile",
        userScore: 'user score'
    },
    ar: {
        movies: 'أفلام',
        tvShows: 'مسلسلات',
        people: 'أشخاص',
        popular: 'شائع',
        nowPlaying: 'يعرض حاليا',
        upComing: 'قادم',
        topRated: 'الأعلى تقييما',
        airingToday: 'يعرض اليوم',
        onTv: 'علي التلفاز',
        search: 'ابحث',
        welcome: 'مرحبا',
        millionsOf:'ملايين الأفلام والمسلسلات والأشخاص جاهزين للاستكشاف. استكشف الآن.',
        today: 'اليوم',
        thisWeek: 'هذا الاسبوع',
        trending: 'رائج',
        playTrailer: 'تشغيل المقطع الدعائي',
        overview: 'نظرة عامة',
        freeToWatch: "مجانا للمشاهدة",
        latestTrailer : "احدث المقاطع الدعائية",
        searchPlaceholder: "ابحث عن أفلام, مسلسلات, أشخاص ...",
        streaming: 'يعرض الان',
        forRent: 'للإيجار',
        inTheatres : "في السينما",
        allCrew: 'كل الممثلين و فريق العمل',
        viewMore: 'عرض أكثر',
        viewAll: 'عرض كل',
        seriesCast :'الممثلين الأعلى أجرا',
        Recommendations: 'التوصيات',
        similar: 'المتشابه',
        media : 'الوسائط',
        backdrops: 'الخلفيات',
        stills: 'الخلفيات',
        videos: 'الفيديوهات',
        posters: 'الملصقات',
        social: 'اجتماعي',
        reviews: 'المراجعات',
        readAllReviews: 'أقرأ كل المراجعات',
        status: "الحالة",
        originalLanguage: "اللغة الاصلية",
        budget: "الميزانية",
        revenue: "الإيرادات",
        network: "الشبكة",
        keywords: "الكلمات الدالة",
        currentSeason: 'الموسم الأخير',
        seasons: 'المواسم',
        main: 'الرئيسية',
        titles : 'عناوين بديلة',
        castCrew:  'الممثلين وطاقم العمل',
        episodeGroups : 'مجموعه الحلقات',
        releaseDates : 'تواريخ الاصدار',
        translations: 'الترجمات',
        changes: 'التعديلات',
        logos: 'الشعارات',
        fandom: 'المعجبين',
        share: "مشاركة",
        shareLink : "رابط المشاركة",
        biography : "السيرة",
        knownFor: "معروف ب",
        personalInfo : "المعلومات الشخصية",
        knownCredits: "الأعمال المعروفة",
        gender: "الجنس",
        birthday: "تاريخ الميلاد",
        placeOfBirth: "مكان الميلاد",
        alsoKnownAs: "معروف ايضا ب",
        acting: "التمثيل",
        all: "الكل",
        department: "القسم",
        profiles: "الملفات الشخصية",
        userScore: 'تقييم المستخدمين'
       }
}